spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=TechVaultDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=techuser
spring.datasource.password=User123!
spring.jpa.hibernate.ddl-auto=update

# Setează log-urile generale pe ERROR (va afișa doar dacă ceva se strică grav)
logging.level.root=ERROR

# Ascunde detaliile de pornire ale Spring
logging.level.org.springframework=ERROR

# Ascunde detaliile de conexiune ale bazei de date (Hikari)
logging.level.com.zaxxer.hikari=ERROR

# Ascunde interogările SQL automate (dacă nu vrei să le vezi)
spring.jpa.show-sql=false